export * from './actions-schema'

import createClient from 'openapi-fetch'
import type { components, paths } from './actions-schema' // generated by openapi-typescript
import { authMiddleware } from '../auth-middleware'
import { ActionStepTokenClient } from '../../types'

export type PagedActionsSuccessResponse =
  paths['/actions']['get']['responses'][200]['content']['application/json']

export type ActionSuccessResponse =
  paths['/actions/{id}']['get']['responses'][200]['content']['application/json']

export type ActionUpdate = components['schemas']['Update']

export type ActionsClient = ReturnType<typeof createClient<paths>>

export const getActions = async (
  client: ActionsClient,
  page: number = 1,
  pageSize: number = 50,
) => {
  return await client.GET('/actions', {
    params: {
      query: {
        pageSize,
        page,
      },
    },
  })
}

export const getAction = async (client: ActionsClient, id: number) => {
  return await client.GET('/actions/{id}', {
    params: {
      path: {
        id,
      },
    },
  })
}

export const updateAction = async (
  client: ActionsClient,
  id: number,
  body: ActionUpdate,
) => {
  return await client.PUT('/actions/{id}', {
    params: {
      path: {
        id,
      },
    },
    body,
  })
}

export const actionsClient = (tokenClient: ActionStepTokenClient) => {
  const client = createClient<paths>({
    baseUrl: tokenClient.apiapi_url,
  })

  client.use(authMiddleware(tokenClient))

  return {
    getActions: (page: number = 1, pageSize: number = 50) =>
      getActions(client, page, pageSize),
    getAction: (id: number) => getAction(client, id),
    updateAction: (id: number, action: ActionUpdate) =>
      updateAction(client, id, action),
  }
}
