import createClient from 'openapi-fetch'
import type { paths } from './actions-schema' // generated by openapi-typescript
import { authMiddleware } from './auth-middleware'
import { ActionStepTokenClient } from '../types'

// Response obj
export type PagedActionsSuccessResponse =
  paths['/actions']['get']['responses'][200]['content']['application/json']

export type ActionSuccessResponse =
  paths['/actions/{id}']['get']['responses'][200]['content']['application/json']

export type ActionsClient = ReturnType<typeof createClient<paths>>

export const getActions = async (
  client: ActionsClient,
  page: number = 1,
  pageSize: number = 50,
): Promise<PagedActionsSuccessResponse> => {
  const { data } = await client.GET('/actions', {
    params: {
      query: {
        pageSize,
        page,
      },
    },
  })

  return data
}

export const getAction = async (
  client: ActionsClient,
  id: number,
): Promise<ActionSuccessResponse> => {
  const { data } = await client.GET('/actions/{id}', {
    params: {
      path: {
        id,
      },
    },
  })

  return data
}

export const actionsClient = (tokenClient: ActionStepTokenClient) => {
  const client = createClient<paths>({
    baseUrl: tokenClient.apiapi_url,
  })

  client.use(authMiddleware(tokenClient))

  return {
    getActions: (page: number = 1, pageSize: number = 50) =>
      getActions(client, page, pageSize),
    getAction: (id: number) => getAction(client, id),
  }
}
