/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace StepMessages {
  export interface paths {
    '/stepmessages': {
      /** @description Returns a collection of StepMessages. For information on how to construct requests filtering by various properties on a StepMessage please refer to the API Developer Portal. */
      get: {
        responses: {
          /** @description OK. */
          200: {
            content: {
              'application/json': components['schemas']['PagedStepMessage']
            }
          }
        }
      }
    }
    '/stepmessages/{id}': {
      /** @description Returns a single StepMessage. */
      get: {
        parameters: {
          path: {
            /**
             * @description Unique identifier for a StepMessage.
             * @example 113
             */
            id: string
          }
        }
        responses: {
          /** @description OK. */
          200: {
            content: {
              'application/json': components['schemas']['SingleStepMessage']
            }
          }
        }
      }
    }
  }

  export type webhooks = Record<string, never>

  export interface components {
    schemas: {
      SingleStepMessage: {
        stepmessages?: components['schemas']['StepMessage']
        meta?: components['schemas']['PageMetaData']
      }
      PagedStepMessage: {
        stepmessages?: components['schemas']['StepMessage'][]
        meta?: components['schemas']['PageMetaData']
      }
      PageMetaData: {
        paging?: components['schemas']['PagingData']
      }
      PagingData: {
        stepmessages?: components['schemas']['StepMessagePageData']
      }
      StepMessagePageData: {
        /**
         * @description The total number of StepMessages returned by the underlying query.
         * @example 360
         */
        recordCount?: number
        /**
         * @description The total number of pages generated by the underlying query.
         * @example 8
         */
        pageCount?: number
        /**
         * @description The page number for this page of StepMessages.
         * @example 2
         */
        page?: number
        /**
         * @description Page size.
         * @example 50
         */
        pageSize?: number
        /**
         * @description A URL to the previous page of StepMessages.
         * @example https://ap-southeast-2.actionstep.com/api/rest/actions?page=1
         */
        prevPage?: string
        /**
         * @description A URL to the next page of StepMessages.
         * @example https://ap-southeast-2.actionstep.com/api/rest/actions?page=3
         */
        nextPage?: string
      }
      StepMessage: {
        /**
         * @description Unique identifier for the StepMessage.
         * @example "10--1--1
         */
        id?: string
        /**
         * @description Name of the StepMessage.
         * @example Purchase of property at 222 Beach Road.
         */
        method?: 'E-Mail'
        /**
         * @description StepMessage subject.
         * @example action_status | [[action_id]] | Step  3: Contract Review
         */
        subject?: string
        /**
         * @description StepMessage message content.
         * @example *** INSERT MESSAGE BODY ***
         */
        message?: string
        /**
         * @description StepMessage message HTML content.
         * @example <p>*** INSERT MESSAGE BODY ***</p>
         */
        messageHtml?: string
        /**
         * @description Indicates if the message is mandatory
         * @example F
         * @enum {string}
         */
        isMandatory?: 'T' | 'F'
        links?: components['schemas']['StepMessageLinks']
      }
      StepMessageLinks: {
        /**
         * @description Unique identifier of the StepMessage type.
         * @example 6
         */
        actionType?: number
        /**
         * @description Unique identifier of the current workflow step applicable to the StepMessage.
         * @example 21--2
         */
        step?: string
        /**
         * @description Unique identifier of the participant type.
         * @example 123
         */
        fromParticipantType?: string
        /**
         * @description Unique identifier of the participant type.
         * @example 123
         */
        toParticipantType?: string
      }
    }
    responses: never
    parameters: never
    headers: never
    pathItems: never
  }

  export type $defs = Record<string, never>

  export type external = Record<string, never>

  export type operations = Record<string, never>
}
