name: ActionStep NPM Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  
  publish-packages:
    defaults:
      run:
        working-directory: ./monorepo
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish -w actionstep-client
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish -w actionstep-auth-function
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
